# version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
     - NODE_ENV=development
     - MONGO_USER=siddique
     - MONGO_PASSWORD=admin
     - SESSION_SECRET=secret
    command: npm run dev
  mongo:
      environment:
      - MONGO_INITDB_ROOT_USERNAME=siddique
      - MONGO_INITDB_ROOT_PASSWORD=admin  